version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - .env
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://${BACKEND_HOST}:${BACKEND_PORT}
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
